#!/bin/sh
# shでできるように変更したい
# if [[ $1 =~ ([^()]+)(\([[:digit]]{4}年[[:digit]]月[[:digit]]日版\))(.*) ]]; then
#     if [[ ${BASH_REMATCH[2]} =~ $(date "+(%Y年%m月%d日版)") ]]; then
#         :# part2みたいな感じになるようにしたい
#     else
#         cp $1 ${BASH_REMATCH[1]}`date "+(%Y年%m月%d日版)"`${1#${1%%.*}}
#         exit
#     fi
# fi
cp "$1" "${1%%.*}$(date "+(%Y年%m月%d日版)")${1#${1%%.*}}"
