#!/bin/sh

# ファイルの拡張子とそれ以外を抽出
head=${1%%.*}
tail=${1#${1%%.*}}
# 同一ディレクトリに同一日に取ったバックアップがある場合、時刻を追加
if find "$(dirname "$1")" -name "$head$(date "+(%Y年%m月%d日版)")$tail" | grep ".*"; then
    # 日付部は変数dateに格納
    date=$(date "+(%Y年%m月%d日%H時%M分%S秒版)")
else
    date=$(date "+(%Y年%m月%d日版)")
fi

cp -pR "$1" "$head$date$tail"